spring.application.name=ielts
spring.security.oauth2.client.registration.google.client-id=327200468914-sl3jferet91osqnls027j2e7oq7otm5a.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
cmudict.file.path=C:/Users/VinhNQ/Downloads/archive/cmudict-0.7b.txt
spring.data.mongodb.uri=mongodb+srv://nqvinh036:1234@swp.oxnbysr.mongodb.net/SWP?retryWrites=true&w=majority
openai.api.key=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

aws.access.key.id=AKIAWM5JEUMD2TXB6CNY
aws.secret.access.key=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
aws.s3.bucket=swpieltsbucket
aws.s3.region=ap-southeast-1

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ietlsonline.swp.2025@gmail.com
spring.mail.password=cxyauqswponfkgcf
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
jwt.secret=J4gKu2KJ3Z5vP8t5NmE+lw6aD3vJ6GpN1kILUBo=

# VnPay Configuration
vnPay.pay-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnPay.return-url=http://localhost:5173/vnpay-result
vnPay.tmn-code=NN4P08IV
vnPay.secret-key=CQKRB6SIGBWOM7O0MCCDAP4T2KLADNM1
#vnPay.api-url=https://sandbox.vnpayment.vn/merchant_webapi/api/transaction

server.port=8080
server.address=0.0.0.0

management.endpoints.web.exposure.include=health,info

#----------------------------------------------
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.web=DEBUG
logging.level.org.springframework.security.authentication=DEBUG
logging.level.org.springframework.boot.autoconfigure.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG
logging.level.org.springframework.security.oauth2.client=DEBUG
logging.level.org.springframework.security.oauth2.client.registration=DEBUG