spring.application.name=ielts
spring.security.oauth2.client.registration.google.client-id=327200468914-sl3jferet91osqnls027j2e7oq7otm5a.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
momo.api.url=https://test-payment.momo.vn

spring.data.mongodb.uri=mongodb+srv://nqvinh036:1234@swp.oxnbysr.mongodb.net/SWP?retryWrites=true&w=majority

# MoMo Configuration
momo.partner-code= MOMO
momo.access-key=F8BBA842ECF85
momo.secret-key=K951B6PE1waDMi640xX08PD3vg6EkVlz
momo.endpoint=https://test-payment.momo.vn/v2/gateway/api
momo.return-url=http://localhost:5173/
momo.ipn-url=http://localhost:8080/api/payment/ipn-handler
momo.request-type= captureWallet
