spring.application.name=ielts
spring.security.oauth2.client.registration.google.client-id=327200468914-sl3jferet91osqnls027j2e7oq7otm5a.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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

spring.security.oauth2.client.registration.google.redirect-uri-template={baseUrl}/login/oauth2/code/{registrationId}
#spring.data.mongodb.uri=mongodb://localhost:27017/IELTS
spring.data.mongodb.uri=mongodb+srv://nqvinh036:1234@swp.oxnbysr.mongodb.net/SWP?retryWrites=true&w=majority
spring.ai.openai.api-key=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
spring.ai.openai.chat.options.model=gpt-4o-mini
aws.access.key.id=AKIAWM5JEUMD2TXB6CNY
aws.secret.access.key=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
aws.s3.bucket=swpieltsbucket
aws.s3.region=ap-southeast-1